name: Database Keep-Alive

on:
  schedule:
    - cron: '16 6 * * 1,4'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  db-keepalive:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4
      # using npm here so it can use tsx to run the script without adding it to the project since it's only used here
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma client
        run: yarn rw prisma generate

      - name: Run database operations
        run: yarn tsx scripts/dbKeepAlive.ts
